CREATE TABLE account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    money_amount NUMERIC(19, 2) NOT NULL,
    is_closed    BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_account_user_id FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    CONSTRAINT uk_user_login UNIQUE (login)
);

CREATE INDEX idx_account_user_id ON account (user_id);